// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent/agent.proto

package agentv1

import (
	v1 "github.com/vsay/vsay-agent-backend/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent registration
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsInfo        string                 `protobuf:"bytes,3,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	LinuxUser     *LinuxUserInfo         `protobuf:"bytes,5,opt,name=linux_user,json=linuxUser,proto3" json:"linux_user,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetLinuxUser() *LinuxUserInfo {
	if x != nil {
		return x.LinuxUser
	}
	return nil
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LinuxUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           int32                  `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	HasSudo       bool                   `protobuf:"varint,5,opt,name=has_sudo,json=hasSudo,proto3" json:"has_sudo,omitempty"`
	HomeDir       string                 `protobuf:"bytes,6,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	Shell         string                 `protobuf:"bytes,7,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinuxUserInfo) Reset() {
	*x = LinuxUserInfo{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxUserInfo) ProtoMessage() {}

func (x *LinuxUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxUserInfo.ProtoReflect.Descriptor instead.
func (*LinuxUserInfo) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *LinuxUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LinuxUserInfo) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LinuxUserInfo) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *LinuxUserInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *LinuxUserInfo) GetHasSudo() bool {
	if x != nil {
		return x.HasSudo
	}
	return false
}

func (x *LinuxUserInfo) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *LinuxUserInfo) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Restrictions  *CommandRestrictions   `protobuf:"bytes,4,opt,name=restrictions,proto3" json:"restrictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetRestrictions() *CommandRestrictions {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

type CommandRestrictions struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AllowedCommands          []string               `protobuf:"bytes,1,rep,name=allowed_commands,json=allowedCommands,proto3" json:"allowed_commands,omitempty"`
	BlockedCommands          []string               `protobuf:"bytes,2,rep,name=blocked_commands,json=blockedCommands,proto3" json:"blocked_commands,omitempty"`
	SudoAllowedCommands      []string               `protobuf:"bytes,3,rep,name=sudo_allowed_commands,json=sudoAllowedCommands,proto3" json:"sudo_allowed_commands,omitempty"`
	ApprovalRequiredCommands []string               `protobuf:"bytes,4,rep,name=approval_required_commands,json=approvalRequiredCommands,proto3" json:"approval_required_commands,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CommandRestrictions) Reset() {
	*x = CommandRestrictions{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRestrictions) ProtoMessage() {}

func (x *CommandRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRestrictions.ProtoReflect.Descriptor instead.
func (*CommandRestrictions) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CommandRestrictions) GetAllowedCommands() []string {
	if x != nil {
		return x.AllowedCommands
	}
	return nil
}

func (x *CommandRestrictions) GetBlockedCommands() []string {
	if x != nil {
		return x.BlockedCommands
	}
	return nil
}

func (x *CommandRestrictions) GetSudoAllowedCommands() []string {
	if x != nil {
		return x.SudoAllowedCommands
	}
	return nil
}

func (x *CommandRestrictions) GetApprovalRequiredCommands() []string {
	if x != nil {
		return x.ApprovalRequiredCommands
	}
	return nil
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Stats         *v1.ResourceStats      `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStats() *v1.ResourceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Bidirectional streaming messages
type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandOutput
	//	*AgentMessage_Status
	//	*AgentMessage_TerminalOutput
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetTerminalOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TerminalOutput); ok {
			return x.TerminalOutput
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,3,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *StatusUpdate `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type AgentMessage_TerminalOutput struct {
	TerminalOutput *TerminalOutput `protobuf:"bytes,5,opt,name=terminal_output,json=terminalOutput,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_CommandOutput) isAgentMessage_Payload() {}

func (*AgentMessage_Status) isAgentMessage_Payload() {}

func (*AgentMessage_TerminalOutput) isAgentMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *v1.Timestamp          `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats         *v1.ResourceStats      `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() *v1.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetStats() *v1.ResourceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Completed     bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CommandOutput) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandOutput) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *CommandOutput) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Command
	//	*ServerMessage_TerminalInput
	//	*ServerMessage_Config
	//	*ServerMessage_Approval
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerMessage) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *ServerMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ServerMessage) GetApproval() *ApprovalNotification {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Command struct {
	Command *CommandRequest `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerMessage_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,2,opt,name=terminal_input,json=terminalInput,proto3,oneof"`
}

type ServerMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

type ServerMessage_Approval struct {
	Approval *ApprovalNotification `protobuf:"bytes,4,opt,name=approval,proto3,oneof"`
}

func (*ServerMessage_Command) isServerMessage_Payload() {}

func (*ServerMessage_TerminalInput) isServerMessage_Payload() {}

func (*ServerMessage_Config) isServerMessage_Payload() {}

func (*ServerMessage_Approval) isServerMessage_Payload() {}

type CommandRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandId        string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command          string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Env              map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiresApproval bool                   `protobuf:"varint,4,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CommandRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConfigUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Restrictions   *CommandRestrictions   `protobuf:"bytes,1,opt,name=restrictions,proto3" json:"restrictions,omitempty"`
	ForceReconnect bool                   `protobuf:"varint,2,opt,name=force_reconnect,json=forceReconnect,proto3" json:"force_reconnect,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigUpdate) GetRestrictions() *CommandRestrictions {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

func (x *ConfigUpdate) GetForceReconnect() bool {
	if x != nil {
		return x.ForceReconnect
	}
	return false
}

type ApprovalNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Approver      string                 `protobuf:"bytes,3,opt,name=approver,proto3" json:"approver,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalNotification) Reset() {
	*x = ApprovalNotification{}
	mi := &file_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalNotification) ProtoMessage() {}

func (x *ApprovalNotification) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalNotification.ProtoReflect.Descriptor instead.
func (*ApprovalNotification) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ApprovalNotification) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ApprovalNotification) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalNotification) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ApprovalNotification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\rvsay.agent.v1\x1a\x12common/types.proto\"\xbf\x02\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_info\x18\x03 \x01(\tR\x06osInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12;\n" +
	"\n" +
	"linux_user\x18\x05 \x01(\v2\x1c.vsay.agent.v1.LinuxUserInfoR\tlinuxUser\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.vsay.agent.v1.RegisterRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\rLinuxUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x05R\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\x05R\x03gid\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x12\x19\n" +
	"\bhas_sudo\x18\x05 \x01(\bR\ahasSudo\x12\x19\n" +
	"\bhome_dir\x18\x06 \x01(\tR\ahomeDir\x12\x14\n" +
	"\x05shell\x18\a \x01(\tR\x05shell\"\xab\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12F\n" +
	"\frestrictions\x18\x04 \x01(\v2\".vsay.agent.v1.CommandRestrictionsR\frestrictions\"\xdd\x01\n" +
	"\x13CommandRestrictions\x12)\n" +
	"\x10allowed_commands\x18\x01 \x03(\tR\x0fallowedCommands\x12)\n" +
	"\x10blocked_commands\x18\x02 \x03(\tR\x0fblockedCommands\x122\n" +
	"\x15sudo_allowed_commands\x18\x03 \x03(\tR\x13sudoAllowedCommands\x12<\n" +
	"\x1aapproval_required_commands\x18\x04 \x03(\tR\x18approvalRequiredCommands\"b\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x123\n" +
	"\x05stats\x18\x02 \x01(\v2\x1d.vsay.common.v1.ResourceStatsR\x05stats\"Q\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb6\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.vsay.agent.v1.HeartbeatH\x00R\theartbeat\x12E\n" +
	"\x0ecommand_output\x18\x03 \x01(\v2\x1c.vsay.agent.v1.CommandOutputH\x00R\rcommandOutput\x125\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.vsay.agent.v1.StatusUpdateH\x00R\x06status\x12H\n" +
	"\x0fterminal_output\x18\x05 \x01(\v2\x1d.vsay.agent.v1.TerminalOutputH\x00R\x0eterminalOutputB\t\n" +
	"\apayload\"y\n" +
	"\tHeartbeat\x127\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x19.vsay.common.v1.TimestampR\ttimestamp\x123\n" +
	"\x05stats\x18\x02 \x01(\v2\x1d.vsay.common.v1.ResourceStatsR\x05stats\"\x99\x01\n" +
	"\rCommandOutput\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\"@\n" +
	"\fStatusUpdate\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x96\x02\n" +
	"\rServerMessage\x129\n" +
	"\acommand\x18\x01 \x01(\v2\x1d.vsay.agent.v1.CommandRequestH\x00R\acommand\x12E\n" +
	"\x0eterminal_input\x18\x02 \x01(\v2\x1c.vsay.agent.v1.TerminalInputH\x00R\rterminalInput\x125\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.vsay.agent.v1.ConfigUpdateH\x00R\x06config\x12A\n" +
	"\bapproval\x18\x04 \x01(\v2#.vsay.agent.v1.ApprovalNotificationH\x00R\bapprovalB\t\n" +
	"\apayload\"\xe8\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x128\n" +
	"\x03env\x18\x03 \x03(\v2&.vsay.agent.v1.CommandRequest.EnvEntryR\x03env\x12+\n" +
	"\x11requires_approval\x18\x04 \x01(\bR\x10requiresApproval\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x7f\n" +
	"\fConfigUpdate\x12F\n" +
	"\frestrictions\x18\x01 \x01(\v2\".vsay.agent.v1.CommandRestrictionsR\frestrictions\x12'\n" +
	"\x0fforce_reconnect\x18\x02 \x01(\bR\x0eforceReconnect\"\x85\x01\n" +
	"\x14ApprovalNotification\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1a\n" +
	"\bapprover\x18\x03 \x01(\tR\bapprover\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\xf4\x01\n" +
	"\fAgentService\x12K\n" +
	"\bRegister\x12\x1e.vsay.agent.v1.RegisterRequest\x1a\x1f.vsay.agent.v1.RegisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.vsay.agent.v1.HeartbeatRequest\x1a .vsay.agent.v1.HeartbeatResponse\x12G\n" +
	"\x06Stream\x12\x1b.vsay.agent.v1.AgentMessage\x1a\x1c.vsay.agent.v1.ServerMessage(\x010\x01B;Z9github.com/vsay/vsay-agent-backend/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: vsay.agent.v1.RegisterRequest
	(*LinuxUserInfo)(nil),        // 1: vsay.agent.v1.LinuxUserInfo
	(*RegisterResponse)(nil),     // 2: vsay.agent.v1.RegisterResponse
	(*CommandRestrictions)(nil),  // 3: vsay.agent.v1.CommandRestrictions
	(*HeartbeatRequest)(nil),     // 4: vsay.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: vsay.agent.v1.HeartbeatResponse
	(*AgentMessage)(nil),         // 6: vsay.agent.v1.AgentMessage
	(*Heartbeat)(nil),            // 7: vsay.agent.v1.Heartbeat
	(*CommandOutput)(nil),        // 8: vsay.agent.v1.CommandOutput
	(*StatusUpdate)(nil),         // 9: vsay.agent.v1.StatusUpdate
	(*TerminalOutput)(nil),       // 10: vsay.agent.v1.TerminalOutput
	(*ServerMessage)(nil),        // 11: vsay.agent.v1.ServerMessage
	(*CommandRequest)(nil),       // 12: vsay.agent.v1.CommandRequest
	(*TerminalInput)(nil),        // 13: vsay.agent.v1.TerminalInput
	(*ConfigUpdate)(nil),         // 14: vsay.agent.v1.ConfigUpdate
	(*ApprovalNotification)(nil), // 15: vsay.agent.v1.ApprovalNotification
	nil,                          // 16: vsay.agent.v1.RegisterRequest.MetadataEntry
	nil,                          // 17: vsay.agent.v1.CommandRequest.EnvEntry
	(*v1.ResourceStats)(nil),     // 18: vsay.common.v1.ResourceStats
	(*v1.Timestamp)(nil),         // 19: vsay.common.v1.Timestamp
}
var file_agent_agent_proto_depIdxs = []int32{
	1,  // 0: vsay.agent.v1.RegisterRequest.linux_user:type_name -> vsay.agent.v1.LinuxUserInfo
	16, // 1: vsay.agent.v1.RegisterRequest.metadata:type_name -> vsay.agent.v1.RegisterRequest.MetadataEntry
	3,  // 2: vsay.agent.v1.RegisterResponse.restrictions:type_name -> vsay.agent.v1.CommandRestrictions
	18, // 3: vsay.agent.v1.HeartbeatRequest.stats:type_name -> vsay.common.v1.ResourceStats
	7,  // 4: vsay.agent.v1.AgentMessage.heartbeat:type_name -> vsay.agent.v1.Heartbeat
	8,  // 5: vsay.agent.v1.AgentMessage.command_output:type_name -> vsay.agent.v1.CommandOutput
	9,  // 6: vsay.agent.v1.AgentMessage.status:type_name -> vsay.agent.v1.StatusUpdate
	10, // 7: vsay.agent.v1.AgentMessage.terminal_output:type_name -> vsay.agent.v1.TerminalOutput
	19, // 8: vsay.agent.v1.Heartbeat.timestamp:type_name -> vsay.common.v1.Timestamp
	18, // 9: vsay.agent.v1.Heartbeat.stats:type_name -> vsay.common.v1.ResourceStats
	12, // 10: vsay.agent.v1.ServerMessage.command:type_name -> vsay.agent.v1.CommandRequest
	13, // 11: vsay.agent.v1.ServerMessage.terminal_input:type_name -> vsay.agent.v1.TerminalInput
	14, // 12: vsay.agent.v1.ServerMessage.config:type_name -> vsay.agent.v1.ConfigUpdate
	15, // 13: vsay.agent.v1.ServerMessage.approval:type_name -> vsay.agent.v1.ApprovalNotification
	17, // 14: vsay.agent.v1.CommandRequest.env:type_name -> vsay.agent.v1.CommandRequest.EnvEntry
	3,  // 15: vsay.agent.v1.ConfigUpdate.restrictions:type_name -> vsay.agent.v1.CommandRestrictions
	0,  // 16: vsay.agent.v1.AgentService.Register:input_type -> vsay.agent.v1.RegisterRequest
	4,  // 17: vsay.agent.v1.AgentService.Heartbeat:input_type -> vsay.agent.v1.HeartbeatRequest
	6,  // 18: vsay.agent.v1.AgentService.Stream:input_type -> vsay.agent.v1.AgentMessage
	2,  // 19: vsay.agent.v1.AgentService.Register:output_type -> vsay.agent.v1.RegisterResponse
	5,  // 20: vsay.agent.v1.AgentService.Heartbeat:output_type -> vsay.agent.v1.HeartbeatResponse
	11, // 21: vsay.agent.v1.AgentService.Stream:output_type -> vsay.agent.v1.ServerMessage
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	file_agent_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandOutput)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_TerminalOutput)(nil),
	}
	file_agent_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*ServerMessage_Command)(nil),
		(*ServerMessage_TerminalInput)(nil),
		(*ServerMessage_Config)(nil),
		(*ServerMessage_Approval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
